default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8

development:
  <<: *default
  username: root
  password:
  host: 127.0.0.1
  database: book_application

test:
  <<: *default
  username: root
  password:
  host: 127.0.0.1
  database: book_application

production:
  <<: *default
  username: root
  password:
  host: 127.0.0.1
  database: book_application
